spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: boot

kafka:
  topic:
    boot: test
# earliest: automatically reset the offset to the earliest offset
# group-id is an unique string that identifies the consumer group this consumer belongs to. This property is required if the consumer uses either the group management functionality by using subscribe(topic) or the Kafka-based offset management strategy.
# kafka-topic-boot is a variable inside Receiver class